server:
  port: 8888

spring:
  application:
    name: attachment
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
  datasource:
    url: jdbc:mysql://47.105.52.207:3306/attachment?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: Buzhidao.0
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update

swagger:
  enabled: true