server:
  port: 8888

spring:
  application:
    name: attachment

  datasource:
    url: jdbc:mysql://47.105.52.207:3306/attachment?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: 你的用户
    password: 你的数据库密码
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update

swagger:
  enabled: true